import { completenessScore } from "./completeness.ts";
import { uid } from "./format.ts";
import type { Lang, MaritalKind, VaultData } from "./types.ts";
import { emptyWillCustody } from "./will-custody.ts";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export function emptyVault(fullName: string, lang: Lang = "th"): VaultData {
  return {
    profile: { fullName, dateOfBirth: "", city: "", occupation: "" },
    assets: [],
    beneficiaries: [],
    letters: [],
    documents: [],
    wishes: {
      funeral: "",
      restingPlace: "",
      organDonation: false,
      digitalAfterlife: "",
      other: "",
    },
    access: {
      executorName: "",
      executorRole: "",
      executorContact: "",
      emergencyName: "",
      emergencyContact: "",
      checkInDays: 30,
      lastCheckIn: new Date().toISOString(),
      releaseNote: "",
    },
    willCustody: emptyWillCustody(),
    activity: [
      {
        id: uid(),
        at: new Date().toISOString(),
        text: lang === "th" ? `สร้างคลังสำหรับ ${fullName}` : `Vault created for ${fullName}`,
      },
    ],
    createdAt: new Date().toISOString(),
  };
}

export function createDemoVault(lang: Lang): VaultData {
  const ids = {
    spouse: uid(),
    daughter: uid(),
    son: uid(),
    charity: uid(),
    condo: uid(),
    land: uid(),
    kbank: uid(),
    scb: uid(),
    stocks: uid(),
    btc: uid(),
    aia: uid(),
    car: uid(),
    google: uid(),
    line: uid(),
    rolex: uid(),
    art: uid(),
  };

  const th: VaultData = {
    profile: {
      fullName: "สุทธิดา วรวัฒน์",
      dateOfBirth: "1968-03-14",
      city: "กรุงเทพมหานคร",
      occupation: "ผู้ประกอบการ",
    },
    assets: [
      {
        id: ids.condo,
        category: "property",
        name: "คอนโดมิเนียม เอกมัย 2 ห้องนอน",
        institution: "นิติบุคคลอาคารชุด The Reserve",
        identifier: "โฉนด เลขที่ 48291",
        valueThb: 12_500_000,
        location: "เอกมัย, กรุงเทพฯ",
        notes: "ห้อง 14B ชั้น 14 พื้นที่ 78 ตร.ม. ผ่อนชำระครบแล้ว",
        beneficiaryIds: [ids.spouse],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(4),
      },
      {
        id: ids.land,
        category: "property",
        name: "ที่ดินสวนลำไย สันกำแพง",
        institution: "สำนักงานที่ดินเชียงใหม่",
        identifier: "โฉนด เลขที่ 11034",
        valueThb: 8_200_000,
        location: "สันกำแพง, เชียงใหม่ · 2 ไร่",
        notes: "ต้องการให้คงเป็นสวน ไม่ขายใน 10 ปีแรก",
        beneficiaryIds: [ids.son, ids.daughter],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(18),
      },
      {
        id: ids.kbank,
        category: "banking",
        name: "บัญชีออมทรัพย์ กสิกรไทย",
        institution: "ธนาคารกสิกรไทย",
        identifier: "xxx-x-x8391",
        valueThb: 2_430_000,
        location: "สาขาทองหล่อ",
        notes: "บัญชีหลักสำหรับค่าใช้จ่ายครอบครัว",
        beneficiaryIds: [ids.spouse],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(1),
      },
      {
        id: ids.scb,
        category: "investment",
        name: "พอร์ต SCB Private Banking",
        institution: "ไทยพาณิชย์",
        identifier: "PB-20411",
        valueThb: 6_800_000,
        location: "สาขาสยามพารากอน",
        notes: "กองทุนผสม หุ้นกู้ และตราสารหนี้",
        beneficiaryIds: [],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(9),
      },
      {
        id: ids.stocks,
        category: "investment",
        name: "พอร์ตหุ้น SET",
        institution: "หลักทรัพย์บัวหลวง",
        identifier: "บัญชี 77821",
        valueThb: 3_120_000,
        location: "ออนไลน์",
        notes: "PTT, ADVANC, CPALL เป็นหลัก",
        beneficiaryIds: [],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(3),
      },
      {
        id: ids.btc,
        category: "crypto",
        name: "กระเป๋า Bitcoin เย็น",
        institution: "Ledger (self-custody)",
        identifier: "bc1q…k4w9",
        valueThb: 2_900_000,
        location: "ตู้เซฟบ้าน · ลิ้นชักล่าง",
        notes: "ฮาร์ดแวร์วอลเล็ตสีดำ ติดป้าย ‘Garden’",
        beneficiaryIds: [ids.daughter],
        secret: "seed เก็บแยกในซองคราฟต์ที่บ้านเชียงใหม่ ไม่เก็บในคลังนี้",
        marital: "unknown" as const,
        updatedAt: daysAgo(21),
      },
      {
        id: ids.aia,
        category: "insurance",
        name: "ประกันชีวิต AIA Unit Linked",
        institution: "AIA Thailand",
        identifier: "กรมธรรม์ UL-552019",
        valueThb: 1_200_000,
        location: "ตัวแทน: คุณมานี",
        notes: "ทุนประกัน 10,000,000 บาท ผู้รับผลประโยชน์ตามกรมธรรม์",
        beneficiaryIds: [ids.spouse, ids.daughter, ids.son],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(40),
      },
      {
        id: ids.car,
        category: "vehicle",
        name: "Lexus RX 350h",
        institution: "กรมการขนส่งทางบก",
        identifier: "กท 3921",
        valueThb: 2_800_000,
        location: "จอดที่คอนโดเอกมัย",
        notes: "ต่อภาษีเดือนมีนาคม กุญแจสำรองที่บ้านแม่",
        beneficiaryIds: [ids.spouse],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(12),
      },
      {
        id: ids.google,
        category: "digital",
        name: "บัญชี Google (ครอบครัว)",
        institution: "Google",
        identifier: "suttida.w@gmail.com",
        valueThb: 0,
        location: "ออนไลน์",
        notes: "เปิด Inactive Account Manager ส่งต่อให้ลูกสาว",
        beneficiaryIds: [ids.daughter],
        secret: "รหัสผ่านอยู่ที่ตัวจัดการรหัสของ Apple บนเครื่อง Mac",
        marital: "unknown" as const,
        updatedAt: daysAgo(6),
      },
      {
        id: ids.line,
        category: "digital",
        name: "LINE / Facebook / Instagram",
        institution: "Meta / LINE",
        identifier: "sutthida.w",
        valueThb: 0,
        location: "ออนไลน์",
        notes: "ต้องการให้ปิด ไม่สร้างเพจอาลัย",
        beneficiaryIds: [ids.daughter],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(6),
      },
      {
        id: ids.rolex,
        category: "collectible",
        name: "Rolex Datejust 36",
        institution: "Siam Paragon Boutique",
        identifier: "Serial 4D2…91",
        valueThb: 420_000,
        location: "ตู้เซฟบ้าน",
        notes: "ของขวัญวันแต่งงาน ปี 2538 — มอบให้ลูกชาย",
        beneficiaryIds: [ids.son],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(90),
      },
      {
        id: ids.art,
        category: "collectible",
        name: "งานศิลปะร่วมสมัย 4 ชิ้น",
        institution: "คอลเลกชันส่วนตัว",
        identifier: "รายการในแฟ้มศิลปะ",
        valueThb: 850_000,
        location: "ผนังห้องนั่งเล่นคอนโด",
        notes: "รายการและใบรับรองอยู่ในแฟ้มสีครีม",
        beneficiaryIds: [ids.charity],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(50),
      },
    ],
    beneficiaries: [
      {
        id: ids.spouse,
        name: "วิชญ์ วรวัฒน์",
        relationship: "spouse",
        sharePercent: 40,
        email: "wich.w@example.com",
        phone: "081-234-1100",
        notes: "คู่ชีวิต 31 ปี ผู้ตัดสินใจเรื่องบ้าน",
      },
      {
        id: ids.daughter,
        name: "ณิชากร วรวัฒน์",
        relationship: "child",
        sharePercent: 30,
        email: "nicha.w@example.com",
        phone: "089-445-8821",
        notes: "อาศัยที่ลอนดอน ทำงานด้านออกแบบ",
      },
      {
        id: ids.son,
        name: "ภูริทัต วรวัฒน์",
        relationship: "child",
        sharePercent: 20,
        email: "phuri.w@example.com",
        phone: "086-901-3344",
        notes: "ดูแลสวนที่เชียงใหม่",
      },
      {
        id: ids.charity,
        name: "มูลนิธิรามาธิบดี",
        relationship: "charity",
        sharePercent: 10,
        email: "legacy@ra.mahidol.ac.th",
        phone: "02-201-1000",
        notes: "บริจาคเป็นทุนการแพทย์",
      },
    ],
    letters: [
      {
        id: uid(),
        toBeneficiaryId: ids.spouse,
        title: "ถึงวิชญ์",
        body: "รัก\n\nถ้าได้อ่านจดหมายนี้ แสดงว่าฉันได้จากไปแล้ว แต่บ้านหลังนี้และเรื่องเล็ก ๆ ในลิ้นชักยังเป็นของเราทั้งคู่ ขอให้กินข้าวให้ครบมื้อ และอย่าเก็บคอนโดไว้คนเดียวถ้ามันเงียบเกินไป\n\nกุญแจตู้เซฟใบที่สองอยู่ในกล่องชาที่ครัวเชียงใหม่\n\nรักเสมอ\nดา",
        updatedAt: daysAgo(11),
      },
      {
        id: uid(),
        toBeneficiaryId: ids.daughter,
        title: "ถึงณิชา",
        body: "ลูกสาว\n\nอย่าเร่งกลับบ้านถ้างานที่ลอนดอนยังไม่จบ แม่สบายใจที่ลูกมีชีวิตของตัวเอง สวนที่เชียงใหม่ไม่ต้องรีบตัดสินใจ — ไปเดินตอนฝนเพิ่งหยุด แล้วค่อยคิด\n\nรหัสรูปเก่า ๆ อยู่ในอัลบั้มปี 2542 หน้าแรก\n\nภูมิใจในตัวลูกทุกวัน\nแม่",
        updatedAt: daysAgo(11),
      },
      {
        id: uid(),
        toBeneficiaryId: ids.son,
        title: "ถึงภูริ",
        body: "ลูกชาย\n\nนาฬิกาเรือนนั้นเป็นของปู่ก่อนที่จะเป็นของแม่ ใส่ได้ทุกวัน ไม่ต้องเก็บในกล่อง ต้นลำไยต้นที่สามจากประตู เป็นต้นที่แม่ปลูกวันลูกเกิด\n\nดูแลพี่สาวด้วย แม้ลูกจะพูดน้อยกว่าเธอ\n\nแม่",
        updatedAt: daysAgo(11),
      },
    ],
    documents: [
      {
        id: uid(),
        title: "พินัยกรรม ฉบับลงนาม 12 ก.พ. 2568",
        kind: "will",
        notes: "ต้นฉบับอยู่ที่สำนักงานทนายอริยา สำเนาในตู้เซฟบ้าน",
        secret: "",
      },
      {
        id: uid(),
        title: "โฉนดคอนโดเอกมัย + ที่ดินสันกำแพง",
        kind: "deed",
        notes: "แฟ้มสีกรมท่า ชั้นสอง ลิ้นชักซ้าย",
        secret: "",
      },
      {
        id: uid(),
        title: "กรมธรรม์ AIA UL-552019",
        kind: "policy",
        notes: "ตัวแทนคุณมานี โทร 081-000-2299",
        secret: "",
      },
      {
        id: uid(),
        title: "รายการรหัสผ่านหลัก",
        kind: "password",
        notes: "ใช้เฉพาะเมื่อแผนส่งมอบทำงาน",
        secret: "Apple ID: suttida.w@icloud.com — กุญแจสำรองใน YubiKey ลิ้นชักทำงาน",
      },
    ],
    wishes: {
      funeral:
        "ไม่ต้องการงานใหญ่ ตั้งศพบริเวณบ้านไม่เกินหนึ่งวัน แล้วถวายเพลิงที่วัดท่าทอง ดอกไม้สีขาวเท่านั้น ห้ามแถลงข่าว",
      restingPlace: "วัดท่าทอง กรุงเทพฯ · โปรยเถ้าบางส่วนที่สวนสันกำแพง",
      organDonation: true,
      digitalAfterlife:
        "ปิด Facebook และ Instagram ภายใน 30 วัน ไม่สร้างเพจอาลัย Google Photos ส่งมอบให้ณิชา LINE ให้วิชญ์เก็บประวัติแชทครอบครัวไว้หนึ่งปีแล้วลบ",
      other:
        "ไม่ต้องการให้ขายสวนใน 10 ปีแรก หากจำเป็นต้องขาย เงินส่วนนั้นเข้ากองทุนการศึกษาหลาน",
    },
    access: {
      executorName: "อริยา พงศ์ไพศาล",
      executorRole: "ทนายความ · สำนักงานกฎหมายพงศ์ไพศาล",
      executorContact: "02-678-4410 · ariya@pongsailaw.co.th",
      emergencyName: "วิชญ์ วรวัฒน์",
      emergencyContact: "081-234-1100",
      checkInDays: 30,
      lastCheckIn: daysAgo(6),
      releaseNote:
        "เมื่อคลังถูกส่งมอบ ให้เริ่มจากพินัยกรรมและรายชื่อทายาท จากนั้นเปิดจดหมายส่วนตัวก่อนย้ายทรัพย์สิน",
    },
    willCustody: {
      place: "lawyer",
      holderName: "สำนักงานกฎหมายพงศ์ไพศาล",
      holderContact: "02-678-4410 · ariya@pongsailaw.co.th",
      location: "ชั้น 12 อาคารสินธร ถนนวิทยุ กรุงเทพฯ",
      depositedAt: "2025-02-12",
      reference: "PP-WILL-2568-12",
      copiesWhere: "ตู้เซฟบ้าน · สำเนาในคลังนี้",
      notes: "ขอต้นฉบับจากคุณอริยาเมื่อยื่นศาล อย่าพึ่งสำเนาในตู้เซฟบ้าน",
    },
    activity: [
      { id: uid(), at: daysAgo(1), text: "อัปเดตยอดบัญชีกสิกรไทย" },
      { id: uid(), at: daysAgo(4), text: "ตรวจโฉนดคอนโดเอกมัย" },
      { id: uid(), at: daysAgo(6), text: "เช็คอินตามแผนส่งมอบ" },
      { id: uid(), at: daysAgo(11), text: "เขียนจดหมายถึงครอบครัว" },
    ],
    createdAt: daysAgo(120),
  };

  const en: VaultData = {
    profile: {
      fullName: "Suttida Worawat",
      dateOfBirth: "1968-03-14",
      city: "Bangkok",
      occupation: "Entrepreneur",
    },
    assets: [
      {
        id: ids.condo,
        category: "property",
        name: "Ekkamai 2-bedroom condominium",
        institution: "The Reserve juristic person",
        identifier: "Title deed 48291",
        valueThb: 12_500_000,
        location: "Ekkamai, Bangkok",
        notes: "Unit 14B, 78 sqm, fully paid.",
        beneficiaryIds: [ids.spouse],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(4),
      },
      {
        id: ids.land,
        category: "property",
        name: "Longan orchard, San Kamphaeng",
        institution: "Chiang Mai Land Office",
        identifier: "Title deed 11034",
        valueThb: 8_200_000,
        location: "San Kamphaeng, Chiang Mai · 2 rai",
        notes: "Keep as an orchard. Do not sell in the first 10 years.",
        beneficiaryIds: [ids.son, ids.daughter],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(18),
      },
      {
        id: ids.kbank,
        category: "banking",
        name: "Kasikorn savings account",
        institution: "Kasikornbank",
        identifier: "xxx-x-x8391",
        valueThb: 2_430_000,
        location: "Thonglor branch",
        notes: "Primary household account.",
        beneficiaryIds: [ids.spouse],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(1),
      },
      {
        id: ids.scb,
        category: "investment",
        name: "SCB Private Banking portfolio",
        institution: "Siam Commercial Bank",
        identifier: "PB-20411",
        valueThb: 6_800_000,
        location: "Siam Paragon branch",
        notes: "Mixed funds, bonds, and bills.",
        beneficiaryIds: [],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(9),
      },
      {
        id: ids.stocks,
        category: "investment",
        name: "SET equity portfolio",
        institution: "Bualuang Securities",
        identifier: "Account 77821",
        valueThb: 3_120_000,
        location: "Online",
        notes: "Core holdings: PTT, ADVANC, CPALL.",
        beneficiaryIds: [],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(3),
      },
      {
        id: ids.btc,
        category: "crypto",
        name: "Bitcoin cold wallet",
        institution: "Ledger (self-custody)",
        identifier: "bc1q…k4w9",
        valueThb: 2_900_000,
        location: "Home safe · lower drawer",
        notes: "Black hardware wallet labelled Garden.",
        beneficiaryIds: [ids.daughter],
        secret: "Seed is in a kraft envelope at the Chiang Mai house — not stored here.",
        marital: "unknown" as const,
        updatedAt: daysAgo(21),
      },
      {
        id: ids.aia,
        category: "insurance",
        name: "AIA unit-linked life policy",
        institution: "AIA Thailand",
        identifier: "Policy UL-552019",
        valueThb: 1_200_000,
        location: "Agent: Manee",
        notes: "THB 10,000,000 sum assured. Beneficiaries per policy.",
        beneficiaryIds: [ids.spouse, ids.daughter, ids.son],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(40),
      },
      {
        id: ids.car,
        category: "vehicle",
        name: "Lexus RX 350h",
        institution: "Department of Land Transport",
        identifier: "กท 3921",
        valueThb: 2_800_000,
        location: "Ekkamai condominium",
        notes: "Tax due in March. Spare key at mother’s house.",
        beneficiaryIds: [ids.spouse],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(12),
      },
      {
        id: ids.google,
        category: "digital",
        name: "Family Google account",
        institution: "Google",
        identifier: "suttida.w@gmail.com",
        valueThb: 0,
        location: "Online",
        notes: "Inactive Account Manager forwards to daughter.",
        beneficiaryIds: [ids.daughter],
        secret: "Password lives in Apple Passwords on the Mac.",
        marital: "unknown" as const,
        updatedAt: daysAgo(6),
      },
      {
        id: ids.line,
        category: "digital",
        name: "LINE / Facebook / Instagram",
        institution: "Meta / LINE",
        identifier: "sutthida.w",
        valueThb: 0,
        location: "Online",
        notes: "Close the accounts. Do not create a memorial page.",
        beneficiaryIds: [ids.daughter],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(6),
      },
      {
        id: ids.rolex,
        category: "collectible",
        name: "Rolex Datejust 36",
        institution: "Siam Paragon Boutique",
        identifier: "Serial 4D2…91",
        valueThb: 420_000,
        location: "Home safe",
        notes: "Wedding gift, 1995 — leave to son.",
        beneficiaryIds: [ids.son],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(90),
      },
      {
        id: ids.art,
        category: "collectible",
        name: "Four contemporary works",
        institution: "Private collection",
        identifier: "Listed in the art folio",
        valueThb: 850_000,
        location: "Condo living room",
        notes: "Certificates in the cream folio.",
        beneficiaryIds: [ids.charity],
        secret: "",
        marital: "unknown" as const,
        updatedAt: daysAgo(50),
      },
    ],
    beneficiaries: [
      {
        id: ids.spouse,
        name: "Witch Worawat",
        relationship: "spouse",
        sharePercent: 40,
        email: "wich.w@example.com",
        phone: "081-234-1100",
        notes: "Partner of 31 years. Decides on the home.",
      },
      {
        id: ids.daughter,
        name: "Nichakorn Worawat",
        relationship: "child",
        sharePercent: 30,
        email: "nicha.w@example.com",
        phone: "089-445-8821",
        notes: "Lives in London. Works in design.",
      },
      {
        id: ids.son,
        name: "Phurithat Worawat",
        relationship: "child",
        sharePercent: 20,
        email: "phuri.w@example.com",
        phone: "086-901-3344",
        notes: "Looks after the Chiang Mai orchard.",
      },
      {
        id: ids.charity,
        name: "Ramathibodi Foundation",
        relationship: "charity",
        sharePercent: 10,
        email: "legacy@ra.mahidol.ac.th",
        phone: "02-201-1000",
        notes: "Gift as a medical fund.",
      },
    ],
    letters: [
      {
        id: uid(),
        toBeneficiaryId: ids.spouse,
        title: "For Witch",
        body: "My love,\n\nIf you are reading this I have gone. The apartment and the small things in the drawers are still ours. Eat proper meals. Do not keep the condo if it is too quiet.\n\nThe second safe key is in the tea tin at the Chiang Mai kitchen.\n\nAlways,\nDa",
        updatedAt: daysAgo(11),
      },
      {
        id: uid(),
        toBeneficiaryId: ids.daughter,
        title: "For Nicha",
        body: "My daughter,\n\nDo not rush home if London is unfinished. I am glad you have a life of your own. The orchard can wait — walk it just after rain, then decide.\n\nThe old photo password is on the first page of the 1999 album.\n\nProud of you every day.\nMae",
        updatedAt: daysAgo(11),
      },
      {
        id: uid(),
        toBeneficiaryId: ids.son,
        title: "For Phuri",
        body: "My son,\n\nThat watch was your grandfather’s before it was mine. Wear it. Do not keep it in a box. The third longan tree from the gate is the one I planted the day you were born.\n\nLook after your sister, even though you speak less than she does.\n\nMae",
        updatedAt: daysAgo(11),
      },
    ],
    documents: [
      {
        id: uid(),
        title: "Will signed 12 Feb 2025",
        kind: "will",
        notes: "Original at Khun Ariya’s office. Copy in the home safe.",
        secret: "",
      },
      {
        id: uid(),
        title: "Ekkamai condo + San Kamphaeng titles",
        kind: "deed",
        notes: "Navy folio, second floor, left drawer.",
        secret: "",
      },
      {
        id: uid(),
        title: "AIA policy UL-552019",
        kind: "policy",
        notes: "Agent Manee, 081-000-2299",
        secret: "",
      },
      {
        id: uid(),
        title: "Primary credentials list",
        kind: "password",
        notes: "Reveal only when the release plan runs.",
        secret: "Apple ID: suttida.w@icloud.com — spare key is the YubiKey in the desk drawer.",
      },
    ],
    wishes: {
      funeral:
        "No large gathering. One day at home, then cremation at Wat That Thong. White flowers only. No press.",
      restingPlace: "Wat That Thong, Bangkok · a portion of ashes at the San Kamphaeng orchard",
      organDonation: true,
      digitalAfterlife:
        "Close Facebook and Instagram within 30 days. No memorial page. Google Photos to Nicha. LINE family history kept by Witch for one year, then deleted.",
      other:
        "Do not sell the orchard in the first 10 years. If it must be sold, that money funds the grandchildren’s education.",
    },
    access: {
      executorName: "Ariya Pongpaisan",
      executorRole: "Counsel · Pongpaisan Law",
      executorContact: "02-678-4410 · ariya@pongsailaw.co.th",
      emergencyName: "Witch Worawat",
      emergencyContact: "081-234-1100",
      checkInDays: 30,
      lastCheckIn: daysAgo(6),
      releaseNote:
        "When the vault is released, start with the will and the heir list. Open the private letters before moving assets.",
    },
    willCustody: {
      place: "lawyer",
      holderName: "Pongpaisan Law",
      holderContact: "02-678-4410 · ariya@pongsailaw.co.th",
      location: "12th floor, Sindhorn Building, Wireless Road, Bangkok",
      depositedAt: "2025-02-12",
      reference: "PP-WILL-2568-12",
      copiesWhere: "Home safe · copy in this vault",
      notes: "Ask Khun Ariya for the original when filing with the court. Do not rely on the home-safe copy.",
    },
    activity: [
      { id: uid(), at: daysAgo(1), text: "Updated Kasikorn savings balance" },
      { id: uid(), at: daysAgo(4), text: "Reviewed Ekkamai title deed" },
      { id: uid(), at: daysAgo(6), text: "Checked in on the release plan" },
      { id: uid(), at: daysAgo(11), text: "Wrote letters to the family" },
    ],
    createdAt: daysAgo(120),
  };

  const vault = lang === "th" ? th : en;
  const maritalOf: Record<string, MaritalKind> = {
    [ids.condo]: "marital",
    [ids.land]: "separate",
    [ids.kbank]: "marital",
    [ids.scb]: "marital",
    [ids.stocks]: "marital",
    [ids.btc]: "unknown",
    [ids.aia]: "unknown",
    [ids.car]: "marital",
    [ids.google]: "separate",
    [ids.line]: "separate",
    [ids.rolex]: "separate",
    [ids.art]: "marital",
  };
  const tagged: VaultData = {
    ...vault,
    assets: vault.assets.map((a) => ({ ...a, marital: maritalOf[a.id] ?? a.marital })),
  };
  void completenessScore(tagged);
  return tagged;
}
