/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as VaultIndexRouteImport } from './routes/vault/index'
import { Route as VaultAccessRouteImport } from './routes/vault/access'
import { Route as VaultAssetsRouteImport } from './routes/vault/assets'
import { Route as VaultDocsRouteImport } from './routes/vault/docs'
import { Route as VaultHeirsRouteImport } from './routes/vault/heirs'
import { Route as VaultWishesRouteImport } from './routes/vault/wishes'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDeadmanTickRouteImport } from './routes/api/deadman/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const VaultAccessRoute = VaultAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => VaultRoute,
} as any)
const VaultAssetsRoute = VaultAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => VaultRoute,
} as any)
const VaultDocsRoute = VaultDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => VaultRoute,
} as any)
const VaultHeirsRoute = VaultHeirsRouteImport.update({
  id: '/heirs',
  path: '/heirs',
  getParentRoute: () => VaultRoute,
} as any)
const VaultWishesRoute = VaultWishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => VaultRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeadmanTickRoute = ApiDeadmanTickRouteImport.update({
  id: '/api/deadman/tick',
  path: '/api/deadman/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/vault': typeof VaultRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/vault/access': typeof VaultAccessRoute
  '/vault/assets': typeof VaultAssetsRoute
  '/vault/docs': typeof VaultDocsRoute
  '/vault/heirs': typeof VaultHeirsRoute
  '/vault/wishes': typeof VaultWishesRoute
  '/legal/': typeof LegalIndexRoute
  '/vault/': typeof VaultIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/deadman/tick': typeof ApiDeadmanTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/vault/access': typeof VaultAccessRoute
  '/vault/assets': typeof VaultAssetsRoute
  '/vault/docs': typeof VaultDocsRoute
  '/vault/heirs': typeof VaultHeirsRoute
  '/vault/wishes': typeof VaultWishesRoute
  '/legal': typeof LegalIndexRoute
  '/vault': typeof VaultIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/deadman/tick': typeof ApiDeadmanTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/vault': typeof VaultRouteWithChildren
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/vault/access': typeof VaultAccessRoute
  '/vault/assets': typeof VaultAssetsRoute
  '/vault/docs': typeof VaultDocsRoute
  '/vault/heirs': typeof VaultHeirsRoute
  '/vault/wishes': typeof VaultWishesRoute
  '/legal/': typeof LegalIndexRoute
  '/vault/': typeof VaultIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/deadman/tick': typeof ApiDeadmanTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/login'
    | '/vault'
    | '/legal/privacy'
    | '/legal/terms'
    | '/vault/access'
    | '/vault/assets'
    | '/vault/docs'
    | '/vault/heirs'
    | '/vault/wishes'
    | '/legal/'
    | '/vault/'
    | '/api/auth/$'
    | '/api/deadman/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/legal/privacy'
    | '/legal/terms'
    | '/vault/access'
    | '/vault/assets'
    | '/vault/docs'
    | '/vault/heirs'
    | '/vault/wishes'
    | '/legal'
    | '/vault'
    | '/api/auth/$'
    | '/api/deadman/tick'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/login'
    | '/vault'
    | '/legal/privacy'
    | '/legal/terms'
    | '/vault/access'
    | '/vault/assets'
    | '/vault/docs'
    | '/vault/heirs'
    | '/vault/wishes'
    | '/legal/'
    | '/vault/'
    | '/api/auth/$'
    | '/api/deadman/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  VaultRoute: typeof VaultRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDeadmanTickRoute: typeof ApiDeadmanTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/vault/': {
      id: '/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/access': {
      id: '/vault/access'
      path: '/access'
      fullPath: '/vault/access'
      preLoaderRoute: typeof VaultAccessRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/assets': {
      id: '/vault/assets'
      path: '/assets'
      fullPath: '/vault/assets'
      preLoaderRoute: typeof VaultAssetsRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/docs': {
      id: '/vault/docs'
      path: '/docs'
      fullPath: '/vault/docs'
      preLoaderRoute: typeof VaultDocsRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/heirs': {
      id: '/vault/heirs'
      path: '/heirs'
      fullPath: '/vault/heirs'
      preLoaderRoute: typeof VaultHeirsRouteImport
      parentRoute: typeof VaultRoute
    }
    '/vault/wishes': {
      id: '/vault/wishes'
      path: '/wishes'
      fullPath: '/vault/wishes'
      preLoaderRoute: typeof VaultWishesRouteImport
      parentRoute: typeof VaultRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deadman/tick': {
      id: '/api/deadman/tick'
      path: '/api/deadman/tick'
      fullPath: '/api/deadman/tick'
      preLoaderRoute: typeof ApiDeadmanTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface VaultRouteChildren {
  VaultAccessRoute: typeof VaultAccessRoute
  VaultAssetsRoute: typeof VaultAssetsRoute
  VaultDocsRoute: typeof VaultDocsRoute
  VaultHeirsRoute: typeof VaultHeirsRoute
  VaultWishesRoute: typeof VaultWishesRoute
  VaultIndexRoute: typeof VaultIndexRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultAccessRoute: VaultAccessRoute,
  VaultAssetsRoute: VaultAssetsRoute,
  VaultDocsRoute: VaultDocsRoute,
  VaultHeirsRoute: VaultHeirsRoute,
  VaultWishesRoute: VaultWishesRoute,
  VaultIndexRoute: VaultIndexRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  VaultRoute: VaultRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDeadmanTickRoute: ApiDeadmanTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
